#!/usr/bin/env node

let process = require('process');
let child_process = require('child_process');
const {
  ESLint
} = require("eslint");

function exec(name) {
  // eslint-disable-next-line no-async-promise-executor
  return new Promise(async resolve => {
    await child_process.exec(name, resolve);
  })
}

(async function main() {
  const eslint = new ESLint({
    fix: false,
    extensions: ['.js'],
  });
  await exec("git stash push -k");

  const results = await eslint.lintFiles('**/*.js');

  await exec("git stash pop");

  const formatter = await eslint.loadFormatter("stylish");
  const resultText = formatter.format(results);

  console.error(resultText);

  for (let result of results) {
    if (result.errorCount) {
      process.exitCode = 1;
    }
  }

})().catch((error) => {
  process.exitCode = 1;
  console.error(error);
});
